// Code generated by sqlc. DO NOT EDIT.
// source: link.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links(id,url)
VALUES($1, $2)
RETURNING id, url
`

type CreateLinkParams struct {
	ID  string `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.queryRow(ctx, q.createLinkStmt, createLink, arg.ID, arg.Url)
	var i Link
	err := row.Scan(&i.ID, &i.Url)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, url
FROM links
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLink(ctx context.Context, id string) (Link, error) {
	row := q.queryRow(ctx, q.getLinkStmt, getLink, id)
	var i Link
	err := row.Scan(&i.ID, &i.Url)
	return i, err
}
