// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	GetLink(ctx context.Context, id string) (Link, error)
}

var _ Querier = (*Queries)(nil)
